[package]
name = "ecc-point-comp-decomp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = "0.29.0"
rand = "0.8.4"
rand_core = { version = "0.6", features = ["getrandom"] }